/* Generated by kol-content/prompt-builder/build_data.py from prompt-lib-hk/prompts.md — do not edit by hand. */
window.PB_DATA = {
 "source": "prompts-hk (30 條免費香港 Prompt)",
 "updated": "2026-09-25",
 "categories": [
  {
   "id": "1",
   "name": "返工 WhatsApp／電郵",
   "prompts": [
    {
     "id": "1-1",
     "num": "1.1",
     "title": "改短內部電郵（書面中文）",
     "scene": "行政／PM 日日回內部 email，想短、有行動項、唔加新承諾。",
     "template": "你係香港寫字樓行政助理，用書面中文回覆。\n任務：將以下草稿改成【客氣／直接】語氣，長度【約 80／120】字內。\n必須保留：所有日期、人名、會議連結狀態。\n禁止：加我冇講過嘅折扣、deadline 或法律承諾；唔好用過多客套開場。\n格式：先一句目的 → 再列點行動 → 最後一句跟進人／期限。\n草稿：\n【貼上草稿】",
     "tool": "ChatGPT — 改語氣同電郵草稿夠快，適合日日用。",
     "toolName": "ChatGPT",
     "toolLearn": "learn/chatgpt/",
     "privacy": "遮公司未公開項目名、客人真名（可改「客戶 A」）。",
     "fields": [
      {
       "label": "語氣",
       "type": "radio",
       "options": [
        "客氣",
        "直接"
       ],
       "raw": "客氣／直接"
      },
      {
       "label": "長度",
       "type": "radio",
       "options": [
        "約 80",
        "約 120"
       ],
       "raw": "約 80／120"
      },
      {
       "label": "你嘅草稿",
       "type": "area",
       "example": "例如：Hi all，週五 3pm 會議改到週一 10am，請各位更新日曆，簡報由客戶 A 準備……",
       "warn": "⚠ 遮公司未公開項目名同客人真名（可改「客戶 A」）。",
       "raw": "貼上草稿"
      }
     ]
    },
    {
     "id": "1-2",
     "num": "1.2",
     "title": "WhatsApp 追貨／改期（粵語口語可發）",
     "scene": "同供應商／同事用 WhatsApp 追貨期，想清楚又唔好太硬。",
     "template": "角色：香港中小企採購。\n幫我寫一則 WhatsApp，【口語粵語／書面中文】，120 字內。\n目的：追【貨品／文件】，原定【日期】，而家想知【新貨期／可否分批】。\n限制：唔可以威脅取消訂單；唔好捏造條款。\n背景：【兩句事實，例如已付訂金比例】\n請給 2 個版本：較軟、較直接。",
     "tool": "ChatGPT — 短訊息多版本對比方便。",
     "toolName": "ChatGPT",
     "toolLearn": "learn/chatgpt/",
     "privacy": "唔好貼完整銀行轉帳證明或訂金單編號。",
     "fields": [
      {
       "label": "語言",
       "type": "radio",
       "options": [
        "口語粵語",
        "書面中文"
       ],
       "raw": "口語粵語／書面中文"
      },
      {
       "label": "追咩",
       "type": "radio",
       "options": [
        "貨品",
        "文件"
       ],
       "raw": "貨品／文件"
      },
      {
       "label": "原定日期",
       "type": "text",
       "example": "例如 10 月 3 日",
       "raw": "日期"
      },
      {
       "label": "想知咩",
       "type": "radio",
       "options": [
        "新貨期",
        "可否分批"
       ],
       "raw": "新貨期／可否分批"
      },
      {
       "label": "背景（兩句事實）",
       "type": "area",
       "example": "例如 已付訂金比例 30%；上次交貨遲咗 3 日",
       "warn": "⚠ 唔好貼完整銀行轉帳證明或訂金單編號。",
       "raw": "兩句事實，例如已付訂金比例"
      }
     ]
    },
    {
     "id": "1-3",
     "num": "1.3",
     "title": "婉拒加班／額外工作",
     "scene": "想禮貌拒絕臨時加班，同時提出可代替方案。",
     "template": "用書面中文寫一封內部回覆給【上司／同事】。\n目的：婉拒【今晚／週末】加班做【任務】。\n原因（只可用我提供嘅）：【例如已有預先約定／同日有客戶交付】。\n可代替方案：【例如週一早交初稿／轉交同事 B】。\n語氣得體、唔道歉過剩、唔投訴。150 字內。\n原文請求：\n【貼上對方訊息】",
     "tool": "Claude — 長一點嘅溝通改稿較穩陣、少加戲。",
     "toolName": "Claude",
     "toolLearn": "learn/claude/",
     "privacy": "唔好寫同事私人事或健康細節。",
     "fields": [
      {
       "label": "回覆對象",
       "type": "radio",
       "options": [
        "上司",
        "同事"
       ],
       "raw": "上司／同事"
      },
      {
       "label": "幾時加班",
       "type": "radio",
       "options": [
        "今晚",
        "週末"
       ],
       "raw": "今晚／週末"
      },
      {
       "label": "要做嘅任務",
       "type": "text",
       "example": "例如 月尾報表",
       "raw": "任務"
      },
      {
       "label": "原因（只寫真實原因）",
       "type": "text",
       "example": "例如 已有預先約定／同日有客戶交付",
       "warn": "⚠ 唔好寫同事私人事或健康細節。",
       "raw": "例如已有預先約定／同日有客戶交付"
      },
      {
       "label": "可代替方案",
       "type": "text",
       "example": "例如 週一早交初稿／轉交同事 B",
       "raw": "例如週一早交初稿／轉交同事 B"
      },
      {
       "label": "對方訊息原文",
       "type": "area",
       "example": "例如：今晚可唔可以留低幫手執埋份報表？",
       "warn": "⚠ 先遮真名、電話、完整地址、身份證號碼同戶口號碼再貼（可用「客人 A」代替）。",
       "raw": "貼上對方訊息"
      }
     ]
    },
    {
     "id": "1-4",
     "num": "1.4",
     "title": "會議邀請＋議程（Google Meet／Teams）",
     "scene": "約內部會議，要議程、時長、會前準備。",
     "template": "幫我寫會議邀請電郵（書面中文）。\n主題：【會議主題】\n時間：【日期時間 + 時區 Asia/Hong_Kong】\n形式：【Google Meet／Teams／面對面，地址只寫大廈名】\n參與者角色：【例如銷售、財務、供應商代表】\n請產出：\n1) 電郵正文（120 字內）\n2) 議程 4 點，每點預計分鐘\n3) 會前請帶：【文件類型，唔好要求貼敏感編號】\n禁止捏造未提供嘅附件連結。",
     "tool": "Gemini — 若你本身用 Google 日曆／Gmail，草稿同後續整理較順。",
     "toolName": "Gemini",
     "toolLearn": "learn/gemini-pdf/",
     "privacy": "會議室門卡密碼、VPN 帳號唔好寫入邀請。",
     "fields": [
      {
       "label": "會議主題",
       "type": "text",
       "example": "例如 Q4 推廣預算檢討",
       "raw": "會議主題"
      },
      {
       "label": "日期時間（香港時間）",
       "type": "text",
       "example": "例如 10 月 8 日（三）下午 3:00 Asia/Hong_Kong",
       "raw": "日期時間 + 時區 Asia/Hong_Kong"
      },
      {
       "label": "形式",
       "type": "list",
       "example": "例如 Teams／面對面（只寫大廈名）",
       "options": [
        "Google Meet",
        "Teams",
        "面對面（只寫大廈名）"
       ],
       "warn": "⚠ 面對面只寫大廈名，唔好寫樓層單位、門卡密碼或 VPN 帳號。",
       "raw": "Google Meet／Teams／面對面，地址只寫大廈名"
      },
      {
       "label": "參與者角色",
       "type": "text",
       "example": "例如 銷售、財務、供應商代表",
       "raw": "例如銷售、財務、供應商代表"
      },
      {
       "label": "會前請帶（文件類型）",
       "type": "text",
       "example": "例如 上季銷售報表、報價草稿",
       "warn": "⚠ 只寫文件類型，唔好要求貼敏感編號。",
       "raw": "文件類型，唔好要求貼敏感編號"
      }
     ]
    },
    {
     "id": "1-5",
     "num": "1.5",
     "title": "會議後跟進（行動項清單）",
     "scene": "開完會要發跟進，對住筆記整理「邊個做咩、幾時」。",
     "template": "你係會議秘書。根據以下筆記，用書面中文輸出：\nA. 3 句會議結論\nB. 行動項表：負責人｜任務｜建議期限｜需其他人提供咩\nC. 未決議題（列點）\n規則：只根據筆記；唔確定就標「待確認」；唔好發明數字或法例。\n筆記：\n【貼上你嘅手寫重點／Notta 摘要，已遮人名可用代號】",
     "tool": "Claude — 適合把零散筆記整理成可發跟進。",
     "toolName": "Claude",
     "toolLearn": "learn/claude/",
     "privacy": "會議錄音轉寫先遮客戶全名同價錢條款再貼。",
     "fields": [
      {
       "label": "會議筆記",
       "type": "area",
       "example": "例如：A 負責報價，下週三前交；B 問供應商交貨期；預算未定，待確認……",
       "warn": "⚠ 已遮人名可用代號；錄音轉寫先遮客戶全名同價錢條款再貼。",
       "raw": "貼上你嘅手寫重點／Notta 摘要，已遮人名可用代號"
      }
     ]
    }
   ]
  },
  {
   "id": "2",
   "name": "搵工",
   "prompts": [
    {
     "id": "2-1",
     "num": "2.1",
     "title": "改 CV 子彈點（香港中英夾雜 JD）",
     "scene": "見到 LinkedIn／JobsDB JD，想將經歷改到對口，又唔吹大。",
     "template": "你係香港職場寫手。根據 JD 同我嘅經歷，改寫 CV 子彈點。\n職位：【職位名】\n公司類型：【例如零售／金融後勤／NGO】\n要求（只摘 JD 關鍵，唔好貼個人聯絡）：\n【貼 5–8 條要求】\n我嘅事實經歷（唔好加我冇做過）：\n【列你真正做過，用量化只限我提供嘅數字】\n輸出：6 條子彈點，每條一行，中英皆可但統一風格；每條含行動動詞＋成果；禁止捏造證書或 GPA。",
     "tool": "ChatGPT — CV 多輪改寫方便。",
     "toolName": "ChatGPT",
     "toolLearn": "learn/chatgpt/",
     "privacy": "遮電話、住址、HKID、完整員工編號。",
     "fields": [
      {
       "label": "職位名",
       "type": "text",
       "example": "例如 Marketing Executive",
       "raw": "職位名"
      },
      {
       "label": "公司類型",
       "type": "text",
       "example": "例如 零售／金融後勤／NGO",
       "raw": "例如零售／金融後勤／NGO"
      },
      {
       "label": "JD 要求（5–8 條）",
       "type": "area",
       "example": "例如：\n- 2 年社交媒體經驗\n- 熟 Canva、Meta Ads\n- 中英文良好",
       "warn": "⚠ 只摘 JD 關鍵，唔好貼招聘人聯絡資料。",
       "raw": "貼 5–8 條要求"
      },
      {
       "label": "你真正做過嘅經歷",
       "type": "area",
       "example": "例如：負責公司 IG，半年由 2k 增至 5k 追蹤；每月出 12 條貼文",
       "warn": "⚠ 遮電話、住址、HKID、完整員工編號；數字只用真實嘅。",
       "raw": "列你真正做過，用量化只限我提供嘅數字"
      }
     ]
    },
    {
     "id": "2-2",
     "num": "2.2",
     "title": "求職信（中小企／初創）",
     "scene": "投香港中小企，要短求職信，突出可立刻上手。",
     "template": "寫一封求職電郵（書面中文，可夾少量英文職位關鍵詞）。\n應徵：【職位】＠【公司類型，唔使寫未公開內部名】\n我嘅賣點 3 個：【】\n可到職：【日期】\n長度：180 字內；結構：點解有興趣 → 點樣幫到 → 邀請面試。\n禁止：誇大薪資期望、捏造推薦人。",
     "tool": "Claude — 求職信語氣較易控到「自信但唔誇」。",
     "toolName": "Claude",
     "toolLearn": "learn/claude/",
     "privacy": "唔好附上舊僱主內部文件截圖。",
     "fields": [
      {
       "label": "應徵職位",
       "type": "text",
       "example": "例如 行政助理",
       "raw": "職位"
      },
      {
       "label": "公司類型",
       "type": "text",
       "example": "例如 本地電商初創（唔使寫未公開內部名）",
       "raw": "公司類型，唔使寫未公開內部名"
      },
      {
       "label": "我嘅賣點 3 個",
       "type": "area",
       "example": "例如 Excel 熟手、識用 Canva 出海報、粵英普流利",
       "raw": ""
      },
      {
       "label": "可到職日期",
       "type": "text",
       "example": "例如 一個月通知期後／11 月 1 日",
       "raw": "日期"
      }
     ]
    },
    {
     "id": "2-3",
     "num": "2.3",
     "title": "面試自我介紹（1 分鐘）",
     "scene": "電話／視像面試前，練一段 1 分鐘自我介紹。",
     "template": "幫我寫面試自我介紹講稿，【粵語口語／書面中文】，約 160–200 字（約 1 分鐘）。\n職位：【】\n背景：【學歷／年資／行業，唔好寫身份證資料】\n想強調：【2 個成就，只用真實數字】\n結尾問一句關於【團隊／職責】嘅問題。\n請標註建議停頓位。",
     "tool": "ChatGPT — 口語稿迭代快。",
     "toolName": "ChatGPT",
     "toolLearn": "learn/chatgpt/",
     "privacy": "唔好講前公司未公開財務數字。",
     "fields": [
      {
       "label": "語言",
       "type": "radio",
       "options": [
        "粵語口語",
        "書面中文"
       ],
       "raw": "粵語口語／書面中文"
      },
      {
       "label": "職位",
       "type": "text",
       "example": "例如 客戶服務主任",
       "raw": ""
      },
      {
       "label": "背景（學歷／年資／行業）",
       "type": "text",
       "example": "例如 大學商科畢業，零售業 3 年",
       "warn": "⚠ 唔好寫身份證資料或前公司未公開財務數字。",
       "raw": "學歷／年資／行業，唔好寫身份證資料"
      },
      {
       "label": "想強調（2 個成就）",
       "type": "area",
       "example": "例如 帶 4 人小組；客戶投訴率半年減 20%（只用真實數字）",
       "raw": "2 個成就，只用真實數字"
      },
      {
       "label": "結尾問題方向",
       "type": "radio",
       "options": [
        "團隊",
        "職責"
       ],
       "raw": "團隊／職責"
      }
     ]
    },
    {
     "id": "2-4",
     "num": "2.4",
     "title": "回覆 HR 約面試（改期／確認）",
     "scene": "HR 約咗時間，你要確認或改期，語氣專業。",
     "template": "用書面中文回覆 HR。\n情況：【確認原定時間／請求改期】\n原定：【日期時間】\n我可選時段（至少 2 個）：【】\n形式：【Zoom／辦公室，只寫地區】\n保留感謝同期待；80 字內；唔好透露其他公司面試詳情。\n對方原文：\n【貼上，遮電郵簽名入面私人手機可】",
     "tool": "Gemini — 短回覆夠用，亦方便喺手機用。",
     "toolName": "Gemini",
     "toolLearn": "learn/gemini-pdf/",
     "privacy": "唔好一次過回覆時附上全套證件掃描。",
     "fields": [
      {
       "label": "情況",
       "type": "radio",
       "options": [
        "確認原定時間",
        "請求改期"
       ],
       "raw": "確認原定時間／請求改期"
      },
      {
       "label": "原定日期時間",
       "type": "text",
       "example": "例如 10 月 8 日（三）上午 10:00",
       "raw": "日期時間"
      },
      {
       "label": "我可選時段（至少 2 個）",
       "type": "text",
       "example": "例如 10/9（四）上午 10 點；10/10（五）下午 3 點",
       "raw": ""
      },
      {
       "label": "形式",
       "type": "list",
       "example": "例如 Zoom／辦公室（只寫地區）",
       "options": [
        "Zoom",
        "辦公室（只寫地區）"
       ],
       "warn": "⚠ 只寫地區，唔好寫完整地址。",
       "raw": "Zoom／辦公室，只寫地區"
      },
      {
       "label": "HR 原文",
       "type": "area",
       "example": "例如：想約你 10 月 8 日上午 10 點面試……",
       "warn": "⚠ 遮電郵簽名入面嘅私人手機同全名再貼。",
       "raw": "貼上，遮電郵簽名入面私人手機可"
      }
     ]
    },
    {
     "id": "2-5",
     "num": "2.5",
     "title": "離職信草稿（私人機構）",
     "scene": "打算遞信，想格式齊、日期清、唔加情緒字。",
     "template": "寫一封私人機構離職信草稿（書面中文）。\n職位：【】\n最後工作日（按我嘅理解）：【日期】——標註「請按僱傭合約／人事政策核實通知期」。\n願意交接：【係／否，範圍一句】\n語氣平穩感謝；唔評論公司或同事；120 字內。\n禁止提供法律意見；提醒我對合約同強積金轉保安排要問人事／受託人。",
     "tool": "Claude — 正式函件較少加戲。",
     "toolName": "Claude",
     "toolLearn": "learn/claude/",
     "privacy": "唔好喺信入面寫新工詳情或客戶名單。",
     "fields": [
      {
       "label": "職位",
       "type": "text",
       "example": "例如 會計文員",
       "raw": ""
      },
      {
       "label": "最後工作日",
       "type": "text",
       "example": "例如 11 月 30 日",
       "raw": "日期"
      },
      {
       "label": "願意交接（係／否＋範圍一句）",
       "type": "text",
       "example": "例如 係，交接現有客戶跟進表同共享文件",
       "warn": "⚠ 唔好寫新工詳情或客戶名單。",
       "raw": "係／否，範圍一句"
      }
     ]
    }
   ]
  },
  {
   "id": "3",
   "name": "屋企同租樓",
   "prompts": [
    {
     "id": "3-1",
     "num": "3.1",
     "title": "睇樓問題清單（私樓／村屋／劏房）",
     "scene": "約睇樓前，想有份唔漏重點嘅問題表。",
     "template": "我喺香港睇【私人樓宇／居屋（注意轉讓限制）／分間樓宇】。\n用途：【自住／投資】\n預算月租或價錢範圍：【只寫區間】\n請用書面中文列出「必問 12 條」，分類：合約、費用（管理費／差餉／地租）、維修、交樓狀況、雜費。\n每條一句；標註邊啲一定要對租約／盤源紙核對。\n唔好叫我提供身份證或銀行戶口。",
     "tool": "ChatGPT — 清單類輸出清楚。",
     "toolName": "ChatGPT",
     "toolLearn": "learn/chatgpt/",
     "privacy": "盤源聊天記錄遮業主全名同完整單位門牌再分享。",
     "fields": [
      {
       "label": "樓宇類型",
       "type": "radio",
       "options": [
        "私人樓宇",
        "居屋（注意轉讓限制）",
        "分間樓宇"
       ],
       "raw": "私人樓宇／居屋（注意轉讓限制）／分間樓宇"
      },
      {
       "label": "用途",
       "type": "radio",
       "options": [
        "自住",
        "投資"
       ],
       "raw": "自住／投資"
      },
      {
       "label": "預算範圍（只寫區間）",
       "type": "text",
       "example": "例如 月租 $12,000–15,000",
       "raw": "只寫區間"
      }
     ]
    },
    {
     "id": "3-2",
     "num": "3.2",
     "title": "租約條款「人話」摘要（已遮敏感）",
     "scene": "收到租約 PDF，想先明白責任，再問律師／地產。",
     "template": "你係文件摘要助手，唔提供法律意見。\n我已遮蓋：姓名、身份證、完整地址、銀行戶口。\n請根據以下租約摘錄，用書面中文列出：\n1) 租期同租金支付方式\n2) 按金同退回條件（只據原文）\n3) 維修責任邊方\n4) 提早解約／加租相關句（原文有先寫）\n5) 我應向【律師／地產／業主】確認嘅 5 條問題\n不確定就寫「原文未見」。\n摘錄：\n【貼上已遮敏段落】",
     "tool": "Gemini — 適合上載長 PDF 後再問（記得先遮敏）。",
     "toolName": "Gemini",
     "toolLearn": "learn/gemini-pdf/",
     "privacy": "上載前一定遮 HKID、完整住址、銀行戶口；輸出唔等於律師意見。",
     "fields": [
      {
       "label": "之後問邊個",
       "type": "radio",
       "options": [
        "律師",
        "地產",
        "業主"
       ],
       "raw": "律師／地產／業主"
      },
      {
       "label": "租約摘錄（已遮敏）",
       "type": "area",
       "example": "例如：第 5 條 租客須於每月 1 日前繳交租金……",
       "warn": "⚠ 貼之前一定遮 HKID、姓名、完整住址同銀行戶口；輸出唔等於律師意見。",
       "raw": "貼上已遮敏段落"
      }
     ]
    },
    {
     "id": "3-3",
     "num": "3.3",
     "title": "聯絡管理處／預約維修",
     "scene": "冷氣／滲水要寫訊息畀管理處或師傅。",
     "template": "寫一則給【管理處／維修商】嘅訊息，書面中文，100 字內。\n大廈：【只寫屋苑名，唔寫座數單位】\n問題：【例如冷氣滴水／公共走廊燈】\n可預約時段：【】\n請要求：回覆預計到場時間、是否要業主證明（如適用）。\n唔好要求對方收集我身份證號碼。",
     "tool": "ChatGPT — 短聯絡訊息夠用。",
     "toolName": "ChatGPT",
     "toolLearn": "learn/chatgpt/",
     "privacy": "WhatsApp 簽名唔好連電話＋全名＋單位一齊轉發公開群。",
     "fields": [
      {
       "label": "寫畀邊個",
       "type": "radio",
       "options": [
        "管理處",
        "維修商"
       ],
       "raw": "管理處／維修商"
      },
      {
       "label": "大廈（只寫屋苑名）",
       "type": "text",
       "example": "例如 太古城",
       "warn": "⚠ 只寫屋苑名，唔好寫座數同單位。",
       "raw": "只寫屋苑名，唔寫座數單位"
      },
      {
       "label": "問題",
       "type": "text",
       "example": "例如 冷氣滴水／公共走廊燈壞",
       "raw": "例如冷氣滴水／公共走廊燈"
      },
      {
       "label": "可預約時段",
       "type": "text",
       "example": "例如 週六上午 10 點至 1 點",
       "raw": ""
      }
     ]
    },
    {
     "id": "3-4",
     "num": "3.4",
     "title": "搬家清單（上班族週末搬）",
     "scene": "租約尾盤搬家，想有清單同時間表。",
     "template": "幫我整一份香港搬家清單（書面中文）。\n搬遷日：【】\n由【區】到【區】；有無電梯：【】\n住人：【】；有無寵物：【只寫有／無】\n輸出：\n- 搬前 14／7／3／1 日待辦\n- 要通知嘅機構類別（寬頻、管理處、銀行通訊地址——只列類別）\n- 紙箱分類建議\n禁止叫我喺 AI 對話貼帳戶號碼。",
     "tool": "ChatGPT — 清單＋日程清晰。",
     "toolName": "ChatGPT",
     "toolLearn": "learn/chatgpt/",
     "privacy": "轉址時官方表格喺銀行／政府網站填，唔好把帳戶資料貼嚟 AI。",
     "fields": [
      {
       "label": "搬遷日",
       "type": "text",
       "example": "例如 11 月 15 日（六）",
       "raw": ""
      },
      {
       "label": "由邊區搬",
       "type": "text",
       "example": "例如 沙田",
       "warn": "⚠ 只寫區，唔好寫完整地址。",
       "raw": "區"
      },
      {
       "label": "搬去邊區",
       "type": "text",
       "example": "例如 將軍澳",
       "warn": "⚠ 只寫區，唔好寫完整地址。",
       "raw": "區"
      },
      {
       "label": "有無電梯",
       "type": "radio",
       "options": [
        "有",
        "無",
        "一邊有一邊無"
       ],
       "raw": ""
      },
      {
       "label": "住人",
       "type": "text",
       "example": "例如 2 大 1 小",
       "raw": ""
      },
      {
       "label": "有無寵物",
       "type": "radio",
       "options": [
        "有",
        "無"
       ],
       "raw": "只寫有／無"
      }
     ]
    },
    {
     "id": "3-5",
     "num": "3.5",
     "title": "解釋差餉／管理費賬單（已遮賬戶）",
     "scene": "收到差餉或管理費通知，想知每項大概係咩。",
     "template": "你係生活行政助手，唔提供稅務／法律意見。\n以下係已遮帳戶號碼同完整姓名嘅帳單文字／OCR。\n請用書面中文：\n1) 逐項解釋「可能係咩費用」（標註不確定）\n2) 邊項應對【差餉物業估價署／管理處】原文\n3) 付款前要核對嘅 4 點\n禁止叫我提供信用卡完整卡號。\n內容：\n【貼上已遮敏文字】",
     "tool": "Gemini — 圖／PDF 帳單解釋方便（先遮敏）。",
     "toolName": "Gemini",
     "toolLearn": "learn/gemini-pdf/",
     "privacy": "遮物業參考編號以外嘅個人識別；金額以官方帳單為準。",
     "fields": [
      {
       "label": "要對邊個嘅原文",
       "type": "radio",
       "options": [
        "差餉物業估價署",
        "管理處"
       ],
       "raw": "差餉物業估價署／管理處"
      },
      {
       "label": "帳單內容（已遮敏）",
       "type": "area",
       "example": "例如：季度差餉 $1,234；物業參考編號 XXXX（已遮）……",
       "warn": "⚠ 遮帳戶號碼、完整姓名、地址再貼；金額以官方帳單為準。",
       "raw": "貼上已遮敏文字"
      }
     ]
    }
   ]
  },
  {
   "id": "4",
   "name": "學生功課",
   "prompts": [
    {
     "id": "4-1",
     "num": "4.1",
     "title": "DSE 長答題大綱（自行作答）",
     "scene": "溫書時要大綱，但最終答案要自己寫，避免交功課抄襲。",
     "template": "你係溫習教練，唔代寫可直接交嘅完整答案。\n科目：【中文／英文／通識類／其他】\n題目：【】\n我而家程度：【】\n請只提供：\n1) 答題結構（段落用途）\n2) 可用論點方向（每點一句，唔寫成範文）\n3) 常見失分位\n4) 3 條我可以自己練習嘅追問\n用書面中文；鼓勵我用自己句子寫全文。",
     "tool": "ChatGPT — 溫習對話互動好。",
     "toolName": "ChatGPT",
     "toolLearn": "learn/chatgpt/",
     "privacy": "唔好上傳學校未公開試卷若校規禁止；遵守學術誠信。",
     "fields": [
      {
       "label": "科目",
       "type": "select",
       "options": [
        "中文",
        "英文",
        "通識類",
        "其他"
       ],
       "raw": "中文／英文／通識類／其他"
      },
      {
       "label": "題目",
       "type": "area",
       "example": "例如 試評論「網上學習能否取代課堂學習」",
       "warn": "⚠ 唔好上傳學校未公開試卷（如校規禁止）。",
       "raw": ""
      },
      {
       "label": "我而家程度",
       "type": "text",
       "example": "例如 中五，議論文結構未穩，平時 3 級左右",
       "raw": ""
      }
     ]
    },
    {
     "id": "4-2",
     "num": "4.2",
     "title": "英文段落改語氣（保留意思）",
     "scene": "論文／報告英文太口語或太亂，想改正式但仍係你嘅意思。",
     "template": "Revise my English paragraph for a Hong Kong 【university／DSE】 assignment.\nGoals: clearer topic sentence, formal academic tone, keep my meaning.\nDo NOT add new citations or facts I did not provide.\nReturn: (1) revised paragraph (2) 5 bullet notes on what changed.\nMy paragraph:\n【paste】",
     "tool": "Claude — 長文改稿同保留原意較穩。",
     "toolName": "Claude",
     "toolLearn": "learn/claude/",
     "privacy": "遮同學全名同學生證號碼。",
     "fields": [
      {
       "label": "功課類型",
       "type": "radio",
       "options": [
        "university",
        "DSE"
       ],
       "raw": "university／DSE"
      },
      {
       "label": "你嘅英文段落",
       "type": "area",
       "example": "e.g. Social media is really bad for teens because they use it too much and...",
       "warn": "⚠ 遮同學全名同學生證號碼。",
       "raw": "paste"
      }
     ]
    },
    {
     "id": "4-3",
     "num": "4.3",
     "title": "小組報告分工表",
     "scene": "專題報告開頭，要公平分工同截止日期。",
     "template": "用書面中文整一份小組報告計劃。\n題目：【】\n人數：【】；截止日期：【】\n成員技能（代號）：【A 擅長資料、B 簡報…】\n輸出：分工表、里程碑（3 個）、風險同後備。\n禁止捏造未讀過嘅學術來源；標註「引用要自己用圖書館／老師指定格式核對」。",
     "tool": "Gemini — 適合之後導出去 Docs 再改。",
     "toolName": "Gemini",
     "toolLearn": "learn/gemini-pdf/",
     "privacy": "用代號代替同學電話。",
     "fields": [
      {
       "label": "報告題目",
       "type": "text",
       "example": "例如 香港即棄膠餐具減用方案",
       "raw": ""
      },
      {
       "label": "人數",
       "type": "text",
       "example": "例如 4",
       "raw": ""
      },
      {
       "label": "截止日期",
       "type": "text",
       "example": "例如 11 月 20 日",
       "raw": ""
      },
      {
       "label": "成員技能（用代號）",
       "type": "area",
       "example": "例如 A 擅長資料、B 簡報、C 寫稿、D 訪問",
       "warn": "⚠ 用代號代替同學全名同電話。",
       "raw": "A 擅長資料、B 簡報…"
      }
     ]
    },
    {
     "id": "4-4",
     "num": "4.4",
     "title": "課堂筆記 → 溫習閃卡",
     "scene": "一堂課筆記太長，想變問答閃卡。",
     "template": "根據筆記產生 12 張溫習閃卡。\n格式：Q: … / A: …\n難度標：基礎／進階\n規則：只據筆記；唔好發明理論；如果筆記矛盾就標「待問老師」。\n筆記：\n【貼上】",
     "tool": "ChatGPT — 閃卡批次生成快。",
     "toolName": "ChatGPT",
     "toolLearn": "learn/chatgpt/",
     "privacy": "錄音堂課前先問清老師准唔准；唔好公開散佈。",
     "fields": [
      {
       "label": "課堂筆記",
       "type": "area",
       "example": "例如：光合作用＝植物用光能將二氧化碳同水變成葡萄糖……",
       "raw": "貼上"
      }
     ]
    },
    {
     "id": "4-5",
     "num": "4.5",
     "title": "簡報講稿（學生報告 3 分鐘）",
     "scene": "要用 Gamma／Canva 簡報，缺講稿。",
     "template": "根據大綱寫 3 分鐘口語講稿（【粵語口語／書面中文】）。\n題目：【】\n大綱：【列 4 點】\n要求：開場一句鉤子、每點約 40 字、結尾問聽眾 1 條問題。\n標註換 slide 位。唔好加我冇嘅數據。",
     "tool": "ChatGPT — 講稿；簡報可用 Gamma／Canva 另做。",
     "toolName": "ChatGPT",
     "toolLearn": "learn/chatgpt/",
     "privacy": "報告若含訪問對象，先徵求同意再記述。",
     "fields": [
      {
       "label": "語言",
       "type": "radio",
       "options": [
        "粵語口語",
        "書面中文"
       ],
       "raw": "粵語口語／書面中文"
      },
      {
       "label": "報告題目",
       "type": "text",
       "example": "例如 香港街頭小食文化",
       "raw": ""
      },
      {
       "label": "大綱（4 點）",
       "type": "area",
       "example": "例如：\n1. 歷史\n2. 代表小食\n3. 面對嘅挑戰\n4. 點樣保育",
       "raw": "列 4 點"
      }
     ]
    }
   ]
  },
  {
   "id": "5",
   "name": "小生意",
   "prompts": [
    {
     "id": "5-1",
     "num": "5.1",
     "title": "IG／WhatsApp 產品文案（本地店）",
     "scene": "茶飲、美容、補習、裝修估價等，要一則可發文案。",
     "template": "你係香港小店文案。寫【IG Caption／WhatsApp 廣播】。\n店類型：【】\n優惠：【真實優惠，唔好發明】\n地區：【】\n語氣：親切、唔誇大療效／回報；如涉食品或美容加「個別效果唔同」。\n輸出：正文 80–120 字 + 3 個 hashtag + 1 句 CTA（例如 DM「價錢」）。\n禁止虛假評論數字。",
     "tool": "ChatGPT — 短文案多版本。",
     "toolName": "ChatGPT",
     "toolLearn": "learn/chatgpt/",
     "privacy": "顧客合照要授權；唔好公開顧客電話。",
     "fields": [
      {
       "label": "發佈位置",
       "type": "radio",
       "options": [
        "IG Caption",
        "WhatsApp 廣播"
       ],
       "raw": "IG Caption／WhatsApp 廣播"
      },
      {
       "label": "店類型",
       "type": "text",
       "example": "例如 手工甜品店",
       "raw": ""
      },
      {
       "label": "優惠（真實優惠）",
       "type": "text",
       "example": "例如 10 月逢星期二買一送一",
       "raw": "真實優惠，唔好發明"
      },
      {
       "label": "地區",
       "type": "text",
       "example": "例如 荃灣",
       "raw": ""
      }
     ]
    },
    {
     "id": "5-2",
     "num": "5.2",
     "title": "報價單說明（服務業）",
     "scene": "出報價前，想用清楚中文解釋項目，減少爭拗。",
     "template": "寫報價說明（書面中文），配套我嘅項目表。\n服務：【】\n項目（名稱｜內容｜單價區間）：【】\n有效期：【】\n包含／不包含：【】\n付款方式：【只寫「轉數快／支票」等類別，唔要帳戶號】\n請加一句：最終以雙方確認報價為準；AI 草稿唔係合約。",
     "tool": "Claude — 條款式文字較謹慎。",
     "toolName": "Claude",
     "toolLearn": "learn/claude/",
     "privacy": "報價 PDF 發送前自己刪草稿入面測試用嘅真實 IBAN／帳戶。",
     "fields": [
      {
       "label": "服務",
       "type": "text",
       "example": "例如 住宅冷氣清洗",
       "raw": ""
      },
      {
       "label": "項目（名稱｜內容｜單價區間）",
       "type": "area",
       "example": "例如 分體機清洗｜拆洗隔塵網＋殺菌｜$380–450",
       "raw": ""
      },
      {
       "label": "有效期",
       "type": "text",
       "example": "例如 報價日起 14 日",
       "raw": ""
      },
      {
       "label": "包含／不包含",
       "type": "area",
       "example": "例如 包：上門費、清潔劑；不包：高空工作台",
       "raw": ""
      },
      {
       "label": "付款方式（只寫類別）",
       "type": "list",
       "example": "例如 轉數快／支票",
       "options": [
        "轉數快",
        "支票",
        "現金",
        "轉數快／支票"
       ],
       "warn": "⚠ 只寫付款類別，唔好填帳戶號碼或 IBAN。",
       "raw": "只寫「轉數快／支票」等類別，唔要帳戶號"
      }
     ]
    },
    {
     "id": "5-3",
     "num": "5.3",
     "title": "顧客投訴回覆（先安撫再方案）",
     "scene": "收到延遲／品質投訴，要公開或私訊回覆草稿。",
     "template": "寫顧客投訴回覆，【書面中文／粵語口語】。\n投訴重點：【】\n我可提供嘅方案（只准用呢啲）：【換貨／部分退款／改期——揀真實可做到】\n禁止：承認未查證嘅法律責任、承諾「一定全額」除非我寫咗。\n結構：致謝 → 重述問題 → 方案 → 跟進時間。120 字內。",
     "tool": "ChatGPT — 客服語氣多版本。",
     "toolName": "ChatGPT",
     "toolLearn": "learn/chatgpt/",
     "privacy": "公開回覆唔好寫出顧客全名同訂單完整電話。",
     "fields": [
      {
       "label": "語言",
       "type": "radio",
       "options": [
        "書面中文",
        "粵語口語"
       ],
       "raw": "書面中文／粵語口語"
      },
      {
       "label": "投訴重點",
       "type": "area",
       "example": "例如 訂單遲咗 5 日先到，蛋糕盒有壓痕",
       "warn": "⚠ 唔好寫顧客全名、電話或完整訂單資料。",
       "raw": ""
      },
      {
       "label": "我可提供嘅方案（可揀多項，只揀真實做到嘅）",
       "type": "multi",
       "options": [
        "換貨",
        "部分退款",
        "改期"
       ],
       "raw": "換貨／部分退款／改期——揀真實可做到"
      }
     ]
    },
    {
     "id": "5-4",
     "num": "5.4",
     "title": "一週內容發佈曆（小編）",
     "scene": "一人店都要維持 IG 更新，想要一週題材。",
     "template": "為【行業】香港小店排 7 日內容曆。\n目標：【詢價／到店／預約】\n每日：題材、格式（短片／圖文）、建議 CTA、拍攝難度（低／中）。\n資源好有限：假設只有手機。\n唔好抄其他品牌商標口號。",
     "tool": "Gemini — 腦力激盪題材快；設計可用 Canva。",
     "toolName": "Gemini",
     "toolLearn": "learn/gemini-pdf/",
     "privacy": "員工出鏡要同意。",
     "fields": [
      {
       "label": "行業",
       "type": "text",
       "example": "例如 美甲",
       "raw": "行業"
      },
      {
       "label": "目標",
       "type": "radio",
       "options": [
        "詢價",
        "到店",
        "預約"
       ],
       "raw": "詢價／到店／預約"
      }
     ]
    },
    {
     "id": "5-5",
     "num": "5.5",
     "title": "進貨／成本筆記整理",
     "scene": "將雜亂進貨筆記整理成表，方便自己對帳（非會計意見）。",
     "template": "將以下進貨筆記整理成表（書面中文）：日期｜供應商代號｜品項｜數量｜單價｜備註。\n只用代號同我提供數字；缺數就空住並標「待補」。\n最後列 3 條我對帳時應問自己嘅問題。\n唔提供稅務／會計意見；提醒保留原單據。\n筆記：\n【】",
     "tool": "ChatGPT — 表格整理。",
     "toolName": "ChatGPT",
     "toolLearn": "learn/chatgpt/",
     "privacy": "供應商完整銀行資料唔好貼。",
     "fields": [
      {
       "label": "進貨筆記",
       "type": "area",
       "example": "例如：9/20 供應商 A 雞蛋 10 箱 $38；9/22 供應商 B 麵粉 5 包（價錢待補）",
       "warn": "⚠ 供應商用代號；唔好貼完整銀行資料。",
       "raw": ""
      }
     ]
    }
   ]
  },
  {
   "id": "6",
   "name": "生活行政（政府表格／保險文件）",
   "prompts": [
    {
     "id": "6-1",
     "num": "6.1",
     "title": "政府表格「填邊欄」導航（已遮個人資料）",
     "scene": "面對長表格，想知每部喺問咩，仍然自己喺官網填。",
     "template": "你係表格導航助手，唔代替提交、唔提供法律意見。\n表格名稱／用途：【例如某類申請，只寫公開名稱】\n我已遮：姓名、HKID、電話、銀行戶口、完整地址。\n請根據以下欄位清單：\n1) 用白話解釋每個部分喺收集咩\n2) 邊啲通常要附件（只屬一般經驗，標「以官網為準」）\n3) 提交前核對清單 6 條\n4) 明確寫：請返【相關政策局／部門官網】下載最新表格同指引\n欄位清單：\n【貼上已遮敏】",
     "tool": "Gemini — 長表格／PDF 分段問。",
     "toolName": "Gemini",
     "toolLearn": "learn/gemini-pdf/",
     "privacy": "永遠唔好把 HKID、銀行戶口貼上 AI；最終以官方表格同指引為準。",
     "fields": [
      {
       "label": "表格名稱／用途（公開名稱）",
       "type": "text",
       "example": "例如 某類津貼申請表",
       "raw": "例如某類申請，只寫公開名稱"
      },
      {
       "label": "相關政策局／部門",
       "type": "text",
       "example": "例如 社會福利署",
       "raw": "相關政策局／部門官網"
      },
      {
       "label": "欄位清單（已遮敏）",
       "type": "area",
       "example": "例如：第一部分 申請人資料；第二部分 住戶成員；第三部分 入息……",
       "warn": "⚠ 永遠唔好貼 HKID、銀行戶口、電話、完整地址；最終以官方表格同指引為準。",
       "raw": "貼上已遮敏"
      }
     ]
    },
    {
     "id": "6-2",
     "num": "6.2",
     "title": "強積金（MPF）轉保／整合前問題清單",
     "scene": "轉工或想整合戶口，先準備問受託人／HR 嘅問題。",
     "template": "用書面中文列出「MPF 轉保／整合前必問 10 條」。\n我情況：【轉工／想整合多個帳戶／只想了解】\n請分類：手續、費用、投資選擇、時間、文件。\n每條問題要係我可以問【僱主人事／受託人熱線】嘅。\n禁止建議具體基金或保證回報；註明：唔構成投資或稅務意見；以積金局同受託人文件為準。",
     "tool": "ChatGPT — 問題清單。",
     "toolName": "ChatGPT",
     "toolLearn": "learn/chatgpt/",
     "privacy": "唔好貼 MPF 戶口完整號碼同登入密碼。",
     "fields": [
      {
       "label": "我嘅情況",
       "type": "radio",
       "options": [
        "轉工",
        "想整合多個帳戶",
        "只想了解"
       ],
       "raw": "轉工／想整合多個帳戶／只想了解"
      },
      {
       "label": "問題係問邊個",
       "type": "radio",
       "options": [
        "僱主人事",
        "受託人熱線"
       ],
       "raw": "僱主人事／受託人熱線"
      }
     ]
    },
    {
     "id": "6-3",
     "num": "6.3",
     "title": "保險續保信／電郵「人話」摘要",
     "scene": "收到續保通知，想知保費變咗咩、要回覆未。",
     "template": "你係文件摘要助手，唔提供保險或財務建議。\n已遮：保單號部分數字、身份證、銀行帳戶、完整住址。\n請摘要：\n1) 續保期限\n2) 保費有無變動（只據原文）\n3) 需要我行動嘅項目\n4) 應向保險公司／持牌顧問確認嘅問題 5 條\n標註：AI 摘要不能取代保單條款。\n原文：\n【】",
     "tool": "Claude — 條款摘要較細心。",
     "toolName": "Claude",
     "toolLearn": "learn/claude/",
     "privacy": "遮保單號碼、HKID、醫療診斷詳情；健康資料尤其唔好亂貼。",
     "fields": [
      {
       "label": "續保信原文（已遮敏）",
       "type": "area",
       "example": "例如：閣下保單將於 2026 年 11 月 1 日續保，新保費為……",
       "warn": "⚠ 遮保單號碼、HKID、銀行帳戶、完整住址同醫療診斷詳情。",
       "raw": ""
      }
     ]
    },
    {
     "id": "6-4",
     "num": "6.4",
     "title": "報稅前文件袋清單（個人）",
     "scene": "報稅季想知要準備咩類型文件（非報稅服務）。",
     "template": "用書面中文整「個人薪俸稅準備清單」（香港）。\n我情況：【受僱／有租金收入／freelance——擇實】\n輸出：文件類型清單、常見扣減類別（只列名稱）、提交前核對 5 點。\n每項旁註：以稅務局當季指引為準。\n禁止計稅、禁止叫我上傳完整薪俸稅表載有 HKID 嘅掃描去 AI。",
     "tool": "ChatGPT — 清單。",
     "toolName": "ChatGPT",
     "toolLearn": "learn/chatgpt/",
     "privacy": "稅表同僱主入息記錄含個人識別，只喺稅務局／認可渠道處理。",
     "fields": [
      {
       "label": "我嘅情況（可揀多項，揀真實）",
       "type": "multi",
       "options": [
        "受僱",
        "有租金收入",
        "freelance"
       ],
       "raw": "受僱／有租金收入／freelance——擇實"
      }
     ]
    },
    {
     "id": "6-5",
     "num": "6.5",
     "title": "簽證／續簽材料「檢查表」（自助核對）",
     "scene": "準備遞交前，想有自我檢查表（非移民顧問意見）。",
     "template": "你係材料檢查助手，唔提供移民法律意見、唔保證獲批。\n申請類型：【例如工作簽證續簽——只寫公開類別】\n我已有材料（類型，唔貼證件圖）：【】\n請輸出：\n1) 一般常見文件類型檢查表（標「以入境處最新指南為準」）\n2) 遞交前格式／相片常見注意（一般性）\n3) 建議我去讀嘅官方來源：入境處網頁\n禁止要求我提供護照號碼、HKID、全套證件影像入對話。",
     "tool": "Gemini — 對住官網指引逐條問較合適。",
     "toolName": "Gemini",
     "toolLearn": "learn/gemini-pdf/",
     "privacy": "證件影像唔好上傳公共 AI；有疑問搵持牌顧問或問入境處。",
     "fields": [
      {
       "label": "申請類型（公開類別）",
       "type": "text",
       "example": "例如 工作簽證續簽",
       "raw": "例如工作簽證續簽——只寫公開類別"
      },
      {
       "label": "我已有材料（只寫類型）",
       "type": "area",
       "example": "例如 僱主信、僱傭合約、稅單、學歷證明",
       "warn": "⚠ 只寫材料類型，唔好貼護照號碼、HKID 或證件影像。",
       "raw": ""
      }
     ]
    }
   ]
  }
 ]
};
